# Custom nginx config
# The default config just return 404 when reload the page which contains uri after the host, eg: http://www.example.com/example
server {
  listen         80;
  listen         [::]:80;

  location / {
    root /usr/share/nginx/html;

    try_files $uri $uri/ /index.html;
  }
}
